// Mock data for frontend development
import { User, Project, Task, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    name: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'jane.smith@example.com',
    name: 'Jane Smith',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    role: 'member',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    email: 'bob.wilson@example.com',
    name: 'Bob Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    role: 'member',
    createdAt: new Date('2024-02-01'),
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete overhaul of company website with modern design',
    owner: mockUsers[0],
    members: mockUsers,
    status: 'active',
    tags: ['design', 'frontend', 'urgent'],
    color: '#5B4EE6',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Native iOS and Android app for customer portal',
    owner: mockUsers[1],
    members: [mockUsers[1], mockUsers[2]],
    status: 'active',
    tags: ['mobile', 'development'],
    color: '#06B6D4',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-14'),
  },
  {
    id: '3',
    name: 'API Integration',
    description: 'Integrate third-party payment and analytics APIs',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[2]],
    status: 'active',
    tags: ['backend', 'integration'],
    color: '#10B981',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-10'),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design homepage mockup',
    description: 'Create high-fidelity mockup for the new homepage design',
    status: 'todo',
    priority: 'high',
    assignees: [mockUsers[1]],
    dueDate: new Date('2024-03-25'),
    projectId: '1',
    order: 0,
    tags: ['design', 'ui'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '2',
    title: 'Implement authentication',
    description: 'Set up JWT authentication with refresh tokens',
    status: 'in-progress',
    priority: 'urgent',
    assignees: [mockUsers[2]],
    dueDate: new Date('2024-03-20'),
    projectId: '1',
    order: 1,
    tags: ['backend', 'security'],
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: '3',
    title: 'Write API documentation',
    description: 'Document all API endpoints with examples',
    status: 'done',
    priority: 'medium',
    assignees: [mockUsers[0]],
    projectId: '3',
    order: 0,
    tags: ['documentation'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-14'),
  },
  {
    id: '4',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment',
    status: 'todo',
    priority: 'low',
    assignees: [mockUsers[2]],
    projectId: '2',
    order: 2,
    tags: ['devops'],
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: '5',
    title: 'User testing session',
    description: 'Conduct usability testing with 5 participants',
    status: 'in-progress',
    priority: 'high',
    assignees: [mockUsers[1], mockUsers[0]],
    dueDate: new Date('2024-03-22'),
    projectId: '2',
    order: 0,
    tags: ['testing', 'ux'],
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-15'),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New task assigned',
    message: 'You have been assigned to "Design homepage mockup"',
    type: 'info',
    read: false,
    userId: '1',
    link: '/projects/1/tasks/1',
    createdAt: new Date('2024-03-16T10:00:00'),
  },
  {
    id: '2',
    title: 'Task completed',
    message: 'Bob Wilson completed "Write API documentation"',
    type: 'success',
    read: false,
    userId: '1',
    link: '/projects/3/tasks/3',
    createdAt: new Date('2024-03-15T14:30:00'),
  },
  {
    id: '3',
    title: 'Deadline approaching',
    message: 'Task "Implement authentication" is due in 2 days',
    type: 'warning',
    read: true,
    userId: '1',
    link: '/projects/1/tasks/2',
    createdAt: new Date('2024-03-14T09:00:00'),
  },
];